// ============================================================
// 公司風格定義 — 20 種企業型態
// ============================================================

export interface CompanyStyle {
  id: string;
  name: string;        // 中文名稱
  nameEn: string;      // 英文名稱
  emoji: string;       // 代表 emoji
  description: string; // 簡短說明（顯示在選擇器中）
  tone: string;        // 給 AI 的語調指示
  gradient: string;    // Tailwind CSS 漸層背景
  textColor: string;   // 文字顏色
}

export const companyStyles: CompanyStyle[] = [
  {
    id: "silicon-valley",
    name: "矽谷新創",
    nameEn: "Silicon Valley Startup",
    emoji: "🚀",
    description: "扁平組織・快節奏・改變世界",
    tone: "充滿活力、使命感強烈。強調 impact、equity、remote-friendly、快速成長、扁平組織、打破常規。使用英文縮寫如 OKR、IPO、MVP 等術語，語調輕鬆但充滿野心。",
    gradient: "from-blue-500 to-indigo-600",
    textColor: "text-blue-700",
  },
  {
    id: "traditional-finance",
    name: "傳統金融",
    nameEn: "Traditional Finance",
    emoji: "🏦",
    description: "穩健嚴謹・精英文化・長期發展",
    tone: "專業、嚴謹、精英感。強調穩定性、職涯發展路徑、完整培訓體系、市場領導地位、合規文化。語調正式但有溫度，突出百年品牌或產業地位。",
    gradient: "from-slate-600 to-gray-800",
    textColor: "text-slate-700",
  },
  {
    id: "esports-gaming",
    name: "熱血電競",
    nameEn: "Esports & Gaming",
    emoji: "🎮",
    description: "熱情・玩中工作・打造爆款",
    tone: "充滿熱情、年輕化、遊戲化語言。強調打造「神作」、玩家思維、熱血團隊、創意自由度、同事都是玩家。可以使用梗語如「無課金」、「破關」等比喻。",
    gradient: "from-purple-500 to-pink-600",
    textColor: "text-purple-700",
  },
  {
    id: "esg-sustainability",
    name: "ESG 永續感",
    nameEn: "ESG & Sustainability",
    emoji: "🌱",
    description: "使命導向・永續未來・正向影響",
    tone: "充滿使命感、溫暖、正向。強調對地球的責任、B-Corp 精神、多元包容、工作的意義與影響力。語調真誠、不浮誇，讓人感受到真實的社會責任。",
    gradient: "from-green-500 to-teal-600",
    textColor: "text-green-700",
  },
  {
    id: "japanese-craftsmanship",
    name: "日系精工",
    nameEn: "Japanese Craftsmanship",
    emoji: "🎌",
    description: "匠人精神・極致品質・細節為王",
    tone: "注重細節、追求極致、匠人精神。強調品質至上、持續改善（Kaizen）、團隊和諧、長期耕耘。語調沉穩、踏實，傳遞「做好每一件小事」的職人哲學。",
    gradient: "from-red-400 to-rose-600",
    textColor: "text-red-700",
  },
  {
    id: "taiwan-tech-mfg",
    name: "台灣科技廠",
    nameEn: "Taiwan Tech Manufacturing",
    emoji: "🔬",
    description: "製造業龍頭・技術底蘊・硬實力",
    tone: "踏實、技術導向、強調硬實力與研發底蘊。突出台灣半導體/製造業的全球地位、技術積累、穩定福利、員工宿舍/三節獎金等台廠特色。語調專業且接地氣。",
    gradient: "from-cyan-500 to-blue-600",
    textColor: "text-cyan-700",
  },
  {
    id: "consulting-mgmt",
    name: "顧問管理",
    nameEn: "Management Consulting",
    emoji: "📊",
    description: "策略思維・菁英培訓・快速晉升",
    tone: "精英感、邏輯清晰、結構化。強調快速成長、與各產業 C-level 合作、解決複雜問題的能力、嚴格培訓體系、強大的校友網絡。語調自信且有說服力。",
    gradient: "from-amber-500 to-orange-600",
    textColor: "text-amber-700",
  },
  {
    id: "healthcare-biotech",
    name: "醫療生技",
    nameEn: "Healthcare & Biotech",
    emoji: "🧬",
    description: "拯救生命・科學前沿・使命為本",
    tone: "充滿使命感、科學嚴謹、溫暖人性。強調工作的意義（改善病患生命）、前沿研究、跨領域合作、嚴謹的科學文化。語調專業且充滿人文關懷。",
    gradient: "from-teal-500 to-cyan-600",
    textColor: "text-teal-700",
  },
  {
    id: "creative-agency",
    name: "創意廣告",
    nameEn: "Creative Agency",
    emoji: "🎨",
    description: "創意無邊・大膽實驗・作品說話",
    tone: "充滿創意、大膽、不拘一格。強調作品集的重要性、創意自由度、與大品牌合作、無聊的地方來了就跳槽。語調跳脫、有個性，甚至可以有點挑釁。",
    gradient: "from-pink-500 to-rose-500",
    textColor: "text-pink-700",
  },
  {
    id: "government-public",
    name: "公務機關",
    nameEn: "Government & Public Sector",
    emoji: "🏛️",
    description: "服務公眾・穩定保障・社會責任",
    tone: "穩重、正式、強調公共服務精神。突出工作穩定性、完整的年金制度、服務社會的使命、清晰的晉升制度。語調莊重且有溫度，讓人感受到工作的社會意義。",
    gradient: "from-stone-500 to-gray-600",
    textColor: "text-stone-700",
  },
  {
    id: "ecommerce-retail",
    name: "電商零售",
    nameEn: "E-commerce & Retail",
    emoji: "🛒",
    description: "數據驅動・高速成長・用戶為王",
    tone: "數據驅動、用戶思維、高速迭代。強調 GMV 成長、用戶體驗、A/B 測試文化、快速決策。語調積極且實戰感強，突出可量化的成果與業績導向文化。",
    gradient: "from-orange-400 to-red-500",
    textColor: "text-orange-700",
  },
  {
    id: "edtech",
    name: "教育科技",
    nameEn: "Education Technology",
    emoji: "📚",
    description: "改變教育・影響未來・學習型組織",
    tone: "充滿理想主義、重視學習成長。強調改變教育現況的使命、學習型組織文化、對下一代的責任。語調溫暖且充滿希望，讓人感受到工作的長遠影響力。",
    gradient: "from-yellow-400 to-amber-500",
    textColor: "text-yellow-700",
  },
  {
    id: "luxury-brand",
    name: "豪華精品",
    nameEn: "Luxury Brand",
    emoji: "💎",
    description: "卓越品味・極致體驗・品牌傳承",
    tone: "優雅、低調奢華、注重品味與卓越。強調品牌傳承、工藝精神、服務極致體驗、與頂級客戶的接觸。語調細膩優雅，避免俗語，用詞精準考究。",
    gradient: "from-yellow-600 to-yellow-800",
    textColor: "text-yellow-800",
  },
  {
    id: "social-enterprise",
    name: "社會企業",
    nameEn: "Social Enterprise",
    emoji: "🤝",
    description: "商業與公益・弱勢關懷・共好文化",
    tone: "充滿溫情、包容多元、相信商業可以改善社會。強調使命優先的商業模式、對弱勢族群的關懷、員工的多元背景。語調真誠、接地氣，讓人感受到真實的溫度。",
    gradient: "from-emerald-400 to-green-600",
    textColor: "text-emerald-700",
  },
  {
    id: "web3-metaverse",
    name: "元宇宙 Web3",
    nameEn: "Web3 & Metaverse",
    emoji: "⛓️",
    description: "去中心化・開放協作・無邊界創新",
    tone: "前衛、去中心化思維、全球視野。強調 Token 激勵、DAO 治理、開放協作、無界限工作方式。使用 Web3 術語如 dApp、smart contract、on-chain 等。語調充滿革命性，感覺在改寫規則。",
    gradient: "from-violet-500 to-purple-700",
    textColor: "text-violet-700",
  },
  {
    id: "multinational-corp",
    name: "外商跨國",
    nameEn: "Multinational Corporate",
    emoji: "🌏",
    description: "國際舞台・跨文化・全球移動",
    tone: "國際化、多元文化、強調全球視野。突出跨國工作機會、外派可能性、與全球同事協作、英語工作環境、完整的全球培訓資源。語調專業且充滿國際感。",
    gradient: "from-blue-400 to-sky-600",
    textColor: "text-blue-700",
  },
  {
    id: "media-publishing",
    name: "媒體出版",
    nameEn: "Media & Publishing",
    emoji: "📰",
    description: "內容為王・說故事・影響輿論",
    tone: "充滿好奇心、重視敘事能力、相信內容的力量。強調新聞自由、獨家報導、說出改變社會的故事、與讀者的真實連結。語調有深度、有溫度，不流於表面。",
    gradient: "from-gray-600 to-zinc-800",
    textColor: "text-gray-700",
  },
  {
    id: "aviation-travel",
    name: "航空旅遊",
    nameEn: "Aviation & Travel",
    emoji: "✈️",
    description: "探索世界・服務熱忱・無限里程",
    tone: "充滿冒險精神、服務至上、讓世界更近。強調機票福利、環遊世界的機會、頂級服務訓練、與全球旅客互動。語調充滿旅遊感與服務熱忱，令人嚮往。",
    gradient: "from-sky-400 to-blue-500",
    textColor: "text-sky-700",
  },
  {
    id: "food-beverage",
    name: "食品餐飲",
    nameEn: "Food & Beverage",
    emoji: "🍽️",
    description: "美食文化・顧客喜悅・創意料理",
    tone: "充滿熱情、重視食材與顧客體驗。強調對食物的熱愛、創造顧客感動的瞬間、師徒傳承、餐飲文化的價值。語調溫馨且充滿生活感，讓人感受到食物帶來的幸福。",
    gradient: "from-orange-400 to-amber-500",
    textColor: "text-orange-700",
  },
  {
    id: "ai-first",
    name: "人工智慧",
    nameEn: "AI-First Company",
    emoji: "🤖",
    description: "AI 原生・智能革命・重新定義產業",
    tone: "前沿技術感、充滿革命性思維。強調 AI-native 文化、LLM/ML 技術深度、用 AI 重新定義產業、與頂尖 AI 研究者共事。使用如 foundation model、inference、RLHF 等術語，充滿技術底蘊。",
    gradient: "from-indigo-500 to-blue-700",
    textColor: "text-indigo-700",
  },
];

export function getStyleById(id: string): CompanyStyle | undefined {
  return companyStyles.find((s) => s.id === id);
}
